"""Emit paper/numbers.tex: one \\newcommand per result so the paper's prose
and tables always reflect the latest results.csv."""

import os

import numpy as np
import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RESULTS_DIR = os.path.join(ROOT, "results")
OUT = os.path.join(ROOT, "paper", "numbers.tex")

DS = {"fmnist": "Fmnist", "cifar10": "Cifar", "bloodmnist": "Blood"}
NOISE = {0.0: "Clean", 0.2: "Noisy"}
METH = {"random": "Random", "entropy": "Entropy", "bald": "Bald",
        "coreset": "Coreset", "learnloss": "Learnloss", "badge": "Badge", "badge-rel": "BadgeRel",
        "iris": "Iris", "iris-grad": "IrisGrad",
        "iris-nodiv": "IrisNodiv", "iris-norel": "IrisNorel"}
# Learning-Loss and BADGE are competitors, not ablations: they must be
# inside the set that "best baseline" is computed over, or every gain
# macro in the paper would silently ignore them.
BASELINES = ["random", "entropy", "bald", "coreset", "learnloss", "badge"]


def main():
    summary = pd.read_csv(os.path.join(RESULTS_DIR, "summary.csv"))
    lines = ["% auto-generated by make_numbers.py -- do not edit"]

    def cmd(name, value):
        lines.append(f"\\newcommand{{\\{name}}}{{{value}}}")

    for _, r in summary.iterrows():
        tag = f"{DS[r.dataset]}{NOISE[r.noise]}{METH[r.method]}"
        cmd(tag + "Final", f"{100 * r.final_acc_mean:.2f}")
        cmd(tag + "FinalStd", f"{100 * r.final_acc_std:.2f}")
        cmd(tag + "Aubc", f"{100 * r.aubc_mean:.2f}")
        cmd(tag + "AubcStd", f"{100 * r.aubc_std:.2f}")

    # IRIS vs best baseline deltas per setting
    for (ds, noise), g in summary.groupby(["dataset", "noise"]):
        iris = g[g.method == "iris"]
        base = g[g.method.isin(BASELINES)]
        if iris.empty or base.empty:
            continue
        tag = f"{DS[ds]}{NOISE[noise]}"
        best_a = base.loc[base.aubc_mean.idxmax()]
        best_f = base.loc[base.final_acc_mean.idxmax()]
        display = {"random": "Random", "entropy": "Entropy",
                   "bald": "BALD", "coreset": "Coreset",
                   "learnloss": "Learning-Loss", "badge": "BADGE",
                   "badge-rel": "BADGE + reliability"}
        cmd(tag + "BestBaseName", display[best_a.method])
        cmd(tag + "IrisAubcGain",
            f"{100 * (iris.iloc[0].aubc_mean - best_a.aubc_mean):+.2f}")
        cmd(tag + "IrisFinalGain",
            f"{100 * (iris.iloc[0].final_acc_mean - best_f.final_acc_mean):+.2f}")

    # paired significance: seeds are matched (same seed -> same initial labeled
    # set), so IRIS and each baseline are compared seed-by-seed.
    from scipy import stats
    res_all = pd.read_csv(os.path.join(RESULTS_DIR, "results.csv"))
    res_all = res_all.drop_duplicates(
        subset=["dataset", "method", "noise", "seed", "round"], keep="last")
    finals = res_all[res_all["round"] == res_all["round"].max()].pivot_table(
        index=["dataset", "noise", "seed"], columns="method", values="test_acc")
    display = {"random": "Random", "entropy": "Entropy",
               "bald": "BALD", "coreset": "Coreset",
               "learnloss": "Learning-Loss", "badge": "BADGE"}
    for (ds, noise), g in finals.groupby(level=[0, 1]):
        if "iris" not in g.columns or g["iris"].isna().any():
            continue
        cands = [m for m in BASELINES if m in g.columns and not g[m].isna().any()]
        if not cands:
            continue
        best = max(cands, key=lambda m: g[m].mean())
        a, b = g["iris"].values, g[best].values
        tag = f"{DS[ds]}{NOISE[noise]}"
        cmd(tag + "BestBaseFinalName", display[best])
        cmd(tag + "NSeeds", f"{len(a)}")
        cmd(tag + "IrisSeedsWon", f"{int((a > b).sum())}/{len(a)}")
        if len(a) > 1 and np.std(a - b) > 0:
            _, pv = stats.ttest_rel(a, b)
            cmd(tag + "IrisPairedP", f"{pv:.3f}")
        else:
            cmd(tag + "IrisPairedP", "--")

    # label savings: the budget at which IRIS first matches the accuracy that
    # random sampling only reaches after spending the whole budget. This is the
    # number an annotation-workflow owner actually cares about.
    res = pd.read_csv(os.path.join(RESULTS_DIR, "results.csv"))
    res = res.drop_duplicates(subset=["dataset", "method", "noise", "seed", "round"],
                              keep="last")
    for (ds, noise), g in res.groupby(["dataset", "noise"]):
        curves = g.groupby(["method", "n_labeled"]).test_acc.mean().unstack()
        if "random" not in curves.index or "iris" not in curves.index:
            continue
        full_budget = curves.columns.max()
        target = curves.loc["random", full_budget]
        iris_c = curves.loc["iris"]
        reached = [n for n in sorted(iris_c.index) if iris_c[n] >= target]
        tag = f"{DS[ds]}{NOISE[noise]}"
        if reached:
            n_match = int(reached[0])
            cmd(tag + "IrisMatchBudget", f"{n_match:,}")
            cmd(tag + "IrisLabelSaving",
                f"{100 * (full_budget - n_match) / full_budget:.0f}")
        else:
            cmd(tag + "IrisMatchBudget", "not reached")
            cmd(tag + "IrisLabelSaving", "0")

    # diagnostics: mean AUROC of introspection head vs entropy (last round, clean)
    diag_path = os.path.join(RESULTS_DIR, "diagnostics.csv")
    if os.path.exists(diag_path):
        dg = pd.read_csv(diag_path)
        dg = dg[dg.method == "iris"]
        for ds, g in dg.groupby("dataset"):
            last = g[g["round"] == g["round"].max()]
            cmd(f"{DS[ds]}AurocIntro",
                f"{100 * np.nanmean(last.auroc_introspection):.1f}")
            cmd(f"{DS[ds]}AurocEnt",
                f"{100 * np.nanmean(last.auroc_entropy):.1f}")

    # ---- round-0 accuracy: the capability-gate proxy quoted in the text and
    # in the dataset table.  Generated, not typed, so it cannot go stale.
    res = pd.read_csv(os.path.join(RESULTS_DIR, "results.csv"))
    r0 = res[res["round"] == 0]
    for ds, tag in DS.items():
        g = r0[r0.dataset == ds]
        if not g.empty:
            cmd(f"{tag}RoundZero", f"{100 * g.test_acc.mean():.0f}")
    # CIFAR-10 spans this accuracy band over the whole budget sweep.
    cif = res[res.dataset == "cifar10"]
    if not cif.empty:
        lo = 100 * cif[cif["round"] == 0].test_acc.mean()
        hi = 100 * (cif[cif["round"] == cif["round"].max()]
                    .groupby("method").test_acc.mean().max())
        cmd("CifarAccLow", f"{lo:.0f}")
        cmd("CifarAccHigh", f"{hi:.0f}")

    # ---- ablation paired tests (IRIS vs its own ablation, matched seeds)
    from scipy import stats as _st
    fin = res[res["round"] == res.groupby(
        ["dataset", "method", "noise", "seed"])["round"].transform("max")]
    for ds, nz, ab, name in [("cifar10", 0.2, "iris-norel", "CifarNoisyNorelPairedP"),
                             ("cifar10", 0.0, "iris-nodiv", "CifarCleanNodivPairedP")]:
        a = fin[(fin.dataset == ds) & (fin.noise == nz) & (fin.method == "iris")]
        b = fin[(fin.dataset == ds) & (fin.noise == nz) & (fin.method == ab)]
        common = sorted(set(a.seed) & set(b.seed))
        if len(common) > 1:
            x = a[a.seed.isin(common)].sort_values("seed").test_acc.values
            y = b[b.seed.isin(common)].sort_values("seed").test_acc.values
            cmd(name, f"{_st.ttest_rel(x, y)[1]:.3f}")

    # ---- the reliability gate measured on a DIFFERENT acquirer.
    # This is the paper's central claim, so it gets its own macros: the lift
    # badge-rel gains over plain badge, per dataset, with a paired test.
    for ds, tag in DS.items():
        a = fin[(fin.dataset == ds) & (fin.noise == 0.2)
                & (fin.method == "badge-rel")]
        b = fin[(fin.dataset == ds) & (fin.noise == 0.2)
                & (fin.method == "badge")]
        common = sorted(set(a.seed) & set(b.seed))
        if len(common) > 1:
            x = a[a.seed.isin(common)].sort_values("seed").test_acc.values * 100
            y = b[b.seed.isin(common)].sort_values("seed").test_acc.values * 100
            cmd(f"{tag}RelOnBadgeGain", f"{x.mean() - y.mean():+.2f}")
            cmd(f"{tag}RelOnBadgeP", f"{_st.ttest_rel(x, y)[1]:.3f}")
            cmd(f"{tag}RelOnBadgeWon", f"{int((x > y).sum())}/{len(common)}")
    # and the same lift measured inside IRIS, for the comparison
    for ds, tag in DS.items():
        a = fin[(fin.dataset == ds) & (fin.noise == 0.2) & (fin.method == "iris")]
        b = fin[(fin.dataset == ds) & (fin.noise == 0.2)
                & (fin.method == "iris-norel")]
        common = sorted(set(a.seed) & set(b.seed))
        if len(common) > 1:
            x = a[a.seed.isin(common)].sort_values("seed").test_acc.values * 100
            y = b[b.seed.isin(common)].sort_values("seed").test_acc.values * 100
            cmd(f"{tag}RelOnIrisGain", f"{x.mean() - y.mean():+.2f}")

    # ---- margin of our learned signal over the prior learned signal
    for ds, tag in DS.items():
        for nz, ntag in ((0.2, "Noisy"), (0.0, "Clean")):
            i = fin[(fin.dataset == ds) & (fin.noise == nz) & (fin.method == "iris")]
            l = fin[(fin.dataset == ds) & (fin.noise == nz)
                    & (fin.method == "learnloss")]
            if len(i) and len(l):
                cmd(f"{tag}{ntag}LearnlossGap",
                    f"{100 * (i.test_acc.mean() - l.test_acc.mean()):+.2f}")

    # ---- parameter cost of the introspection head, per backbone.
    # The head is a fixed d->128->1 MLP, so its share shrinks as the
    # backbone grows; quoting one number for all three would be wrong.
    try:
        import sys as _sys
        _sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
        import torch as _t
        _dev = os.environ.get("CUDA_VISIBLE_DEVICES")
        os.environ["CUDA_VISIBLE_DEVICES"] = ""
        import hitl_experiments as _H
        for ds, tag in DS.items():
            bb, hd = _H.make_model(ds, 0)
            nb = sum(q.numel() for q in bb.parameters())
            nh = sum(q.numel() for q in hd.parameters())
            cmd(f"{tag}HeadPct", f"{100 * nh / (nb + nh):.1f}")
        if _dev is not None:
            os.environ["CUDA_VISIBLE_DEVICES"] = _dev
    except Exception as e:  # torch absent: leave the macros to their fallbacks
        print("skipped head-size macros:", e)

    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({len(lines) - 1} macros)")


if __name__ == "__main__":
    main()
