"""Emit paper/numbers.tex: one \\newcommand per result so the paper's prose
and tables always reflect the latest results.csv."""

import os

import numpy as np
import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RESULTS_DIR = os.path.join(ROOT, "results")
OUT = os.path.join(ROOT, "paper", "numbers.tex")

DS = {"fmnist": "Fmnist", "cifar10": "Cifar", "bloodmnist": "Blood"}
NOISE = {0.0: "Clean", 0.2: "Noisy"}
METH = {"random": "Random", "entropy": "Entropy", "bald": "Bald",
        "coreset": "Coreset", "iris": "Iris",
        "iris-nodiv": "IrisNodiv", "iris-norel": "IrisNorel"}
BASELINES = ["random", "entropy", "bald", "coreset"]


def main():
    summary = pd.read_csv(os.path.join(RESULTS_DIR, "summary.csv"))
    lines = ["% auto-generated by make_numbers.py -- do not edit"]

    def cmd(name, value):
        lines.append(f"\\newcommand{{\\{name}}}{{{value}}}")

    for _, r in summary.iterrows():
        tag = f"{DS[r.dataset]}{NOISE[r.noise]}{METH[r.method]}"
        cmd(tag + "Final", f"{100 * r.final_acc_mean:.2f}")
        cmd(tag + "FinalStd", f"{100 * r.final_acc_std:.2f}")
        cmd(tag + "Aubc", f"{100 * r.aubc_mean:.2f}")
        cmd(tag + "AubcStd", f"{100 * r.aubc_std:.2f}")

    # IRIS vs best baseline deltas per setting
    for (ds, noise), g in summary.groupby(["dataset", "noise"]):
        iris = g[g.method == "iris"]
        base = g[g.method.isin(BASELINES)]
        if iris.empty or base.empty:
            continue
        tag = f"{DS[ds]}{NOISE[noise]}"
        best_a = base.loc[base.aubc_mean.idxmax()]
        best_f = base.loc[base.final_acc_mean.idxmax()]
        display = {"random": "Random", "entropy": "Entropy",
                   "bald": "BALD", "coreset": "Coreset"}
        cmd(tag + "BestBaseName", display[best_a.method])
        cmd(tag + "IrisAubcGain",
            f"{100 * (iris.iloc[0].aubc_mean - best_a.aubc_mean):+.2f}")
        cmd(tag + "IrisFinalGain",
            f"{100 * (iris.iloc[0].final_acc_mean - best_f.final_acc_mean):+.2f}")

    # paired significance: seeds are matched (same seed -> same initial labeled
    # set), so IRIS and each baseline are compared seed-by-seed.
    from scipy import stats
    res_all = pd.read_csv(os.path.join(RESULTS_DIR, "results.csv"))
    res_all = res_all.drop_duplicates(
        subset=["dataset", "method", "noise", "seed", "round"], keep="last")
    finals = res_all[res_all["round"] == res_all["round"].max()].pivot_table(
        index=["dataset", "noise", "seed"], columns="method", values="test_acc")
    display = {"random": "Random", "entropy": "Entropy",
               "bald": "BALD", "coreset": "Coreset"}
    for (ds, noise), g in finals.groupby(level=[0, 1]):
        if "iris" not in g.columns or g["iris"].isna().any():
            continue
        cands = [m for m in BASELINES if m in g.columns and not g[m].isna().any()]
        if not cands:
            continue
        best = max(cands, key=lambda m: g[m].mean())
        a, b = g["iris"].values, g[best].values
        tag = f"{DS[ds]}{NOISE[noise]}"
        cmd(tag + "BestBaseFinalName", display[best])
        cmd(tag + "NSeeds", f"{len(a)}")
        cmd(tag + "IrisSeedsWon", f"{int((a > b).sum())}/{len(a)}")
        if len(a) > 1 and np.std(a - b) > 0:
            _, pv = stats.ttest_rel(a, b)
            cmd(tag + "IrisPairedP", f"{pv:.3f}")
        else:
            cmd(tag + "IrisPairedP", "--")

    # label savings: the budget at which IRIS first matches the accuracy that
    # random sampling only reaches after spending the whole budget. This is the
    # number an annotation-workflow owner actually cares about.
    res = pd.read_csv(os.path.join(RESULTS_DIR, "results.csv"))
    res = res.drop_duplicates(subset=["dataset", "method", "noise", "seed", "round"],
                              keep="last")
    for (ds, noise), g in res.groupby(["dataset", "noise"]):
        curves = g.groupby(["method", "n_labeled"]).test_acc.mean().unstack()
        if "random" not in curves.index or "iris" not in curves.index:
            continue
        full_budget = curves.columns.max()
        target = curves.loc["random", full_budget]
        iris_c = curves.loc["iris"]
        reached = [n for n in sorted(iris_c.index) if iris_c[n] >= target]
        tag = f"{DS[ds]}{NOISE[noise]}"
        if reached:
            n_match = int(reached[0])
            cmd(tag + "IrisMatchBudget", f"{n_match:,}")
            cmd(tag + "IrisLabelSaving",
                f"{100 * (full_budget - n_match) / full_budget:.0f}")
        else:
            cmd(tag + "IrisMatchBudget", "not reached")
            cmd(tag + "IrisLabelSaving", "0")

    # diagnostics: mean AUROC of introspection head vs entropy (last round, clean)
    diag_path = os.path.join(RESULTS_DIR, "diagnostics.csv")
    if os.path.exists(diag_path):
        dg = pd.read_csv(diag_path)
        dg = dg[dg.method == "iris"]
        for ds, g in dg.groupby("dataset"):
            last = g[g["round"] == g["round"].max()]
            cmd(f"{DS[ds]}AurocIntro",
                f"{100 * np.nanmean(last.auroc_introspection):.1f}")
            cmd(f"{DS[ds]}AurocEnt",
                f"{100 * np.nanmean(last.auroc_entropy):.1f}")

    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({len(lines) - 1} macros)")


if __name__ == "__main__":
    main()
